-- Create 3 test orders
-- Make sure to replace customer_id with an actual customer ID from your database

-- Order 1: Hamburg → München
INSERT INTO transport_orders (
    customer_id,
    pickup_address,
    pickup_city,
    pickup_postal_code,
    pickup_contact_name,
    pickup_contact_phone,
    pickup_date,
    pickup_time_from,
    pickup_time_to,
    delivery_address,
    delivery_city,
    delivery_postal_code,
    delivery_contact_name,
    delivery_contact_phone,
    delivery_date,
    delivery_time_from,
    delivery_time_to,
    vehicle_type,
    weight,
    pallets,
    description,
    price,
    status,
    distance_km,
    duration_minutes
) VALUES (
    1, -- Replace with actual customer_id
    'Reeperbahn 154',
    'Hamburg',
    '20359',
    'Klaus Schmidt',
    '+49 40 123456',
    CURRENT_DATE + INTERVAL '2 days',
    '08:00',
    '12:00',
    'Marienplatz 8',
    'München',
    '80331',
    'Maria Weber',
    '+49 89 654321',
    CURRENT_DATE + INTERVAL '2 days',
    '08:00',
    '12:00',
    'Mittlerer Transporter (bis 4 Paletten)',
    350.00,
    3,
    '3 Paletten mit Elektronik',
    520.00,
    'pending',
    775,
    450
);

-- Order 2: Berlin → Frankfurt
INSERT INTO transport_orders (
    customer_id,
    pickup_address,
    pickup_city,
    pickup_postal_code,
    pickup_contact_name,
    pickup_contact_phone,
    pickup_date,
    pickup_time_from,
    pickup_time_to,
    delivery_address,
    delivery_city,
    delivery_postal_code,
    delivery_contact_name,
    delivery_contact_phone,
    delivery_date,
    delivery_time_from,
    delivery_time_to,
    vehicle_type,
    weight,
    pallets,
    description,
    price,
    status,
    distance_km,
    duration_minutes
) VALUES (
    1, -- Replace with actual customer_id
    'Alexanderplatz 1',
    'Berlin',
    '10178',
    'Thomas Müller',
    '+49 30 987654',
    CURRENT_DATE + INTERVAL '3 days',
    '09:00',
    '13:00',
    'Zeil 106',
    'Frankfurt am Main',
    '60313',
    'Anna Fischer',
    '+49 69 456789',
    CURRENT_DATE + INTERVAL '3 days',
    '09:00',
    '13:00',
    'Kleintransporter (bis 2 Paletten)',
    150.00,
    2,
    '2 Paletten mit Büromaterial',
    380.00,
    'pending',
    550,
    320
);

-- Order 3: Köln → Stuttgart
INSERT INTO transport_orders (
    customer_id,
    pickup_address,
    pickup_city,
    pickup_postal_code,
    pickup_contact_name,
    pickup_contact_phone,
    pickup_date,
    pickup_time_from,
    pickup_time_to,
    delivery_address,
    delivery_city,
    delivery_postal_code,
    delivery_contact_name,
    delivery_contact_phone,
    delivery_date,
    delivery_time_from,
    delivery_time_to,
    vehicle_type,
    weight,
    pallets,
    description,
    price,
    status,
    distance_km,
    duration_minutes
) VALUES (
    1, -- Replace with actual customer_id
    'Hohe Straße 1',
    'Köln',
    '50667',
    'Peter Wagner',
    '+49 221 111222',
    CURRENT_DATE + INTERVAL '4 days',
    '10:00',
    '14:00',
    'Königstraße 1A',
    'Stuttgart',
    '70173',
    'Sophie Becker',
    '+49 711 333444',
    CURRENT_DATE + INTERVAL '4 days',
    '10:00',
    '14:00',
    'Großer Transporter (bis 6 Paletten)',
    500.00,
    5,
    '5 Paletten mit Maschinen',
    650.00,
    'pending',
    420,
    280
);

-- Verify the orders were created
SELECT id, pickup_city, delivery_city, price, status, created_at 
FROM transport_orders 
ORDER BY created_at DESC 
LIMIT 3;
